// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockTemplatesRepository is an autogenerated mock type for the TemplatesRepository type
type MockTemplatesRepository struct {
	mock.Mock
}

type MockTemplatesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplatesRepository) EXPECT() *MockTemplatesRepository_Expecter {
	return &MockTemplatesRepository_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: w, name, data
func (_m *MockTemplatesRepository) Render(w io.Writer, name string, data interface{}) error {
	ret := _m.Called(w, name, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, string, interface{}) error); ok {
		r0 = rf(w, name, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTemplatesRepository_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockTemplatesRepository_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - w io.Writer
//   - name string
//   - data interface{}
func (_e *MockTemplatesRepository_Expecter) Render(w interface{}, name interface{}, data interface{}) *MockTemplatesRepository_Render_Call {
	return &MockTemplatesRepository_Render_Call{Call: _e.mock.On("Render", w, name, data)}
}

func (_c *MockTemplatesRepository_Render_Call) Run(run func(w io.Writer, name string, data interface{})) *MockTemplatesRepository_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockTemplatesRepository_Render_Call) Return(_a0 error) *MockTemplatesRepository_Render_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTemplatesRepository_Render_Call) RunAndReturn(run func(io.Writer, string, interface{}) error) *MockTemplatesRepository_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplatesRepository creates a new instance of MockTemplatesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplatesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplatesRepository {
	mock := &MockTemplatesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
