// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	service "github.com/livingpool/service"
	mock "github.com/stretchr/testify/mock"
)

// MockPlayerPoolRepository is an autogenerated mock type for the PlayerPoolRepository type
type MockPlayerPoolRepository struct {
	mock.Mock
}

type MockPlayerPoolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerPoolRepository) EXPECT() *MockPlayerPoolRepository_Expecter {
	return &MockPlayerPoolRepository_Expecter{mock: &_m.Mock}
}

// AddPlayer provides a mock function with given fields: player
func (_m *MockPlayerPoolRepository) AddPlayer(player *service.Player) error {
	ret := _m.Called(player)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*service.Player) error); ok {
		r0 = rf(player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerPoolRepository_AddPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayer'
type MockPlayerPoolRepository_AddPlayer_Call struct {
	*mock.Call
}

// AddPlayer is a helper method to define mock.On call
//   - player *service.Player
func (_e *MockPlayerPoolRepository_Expecter) AddPlayer(player interface{}) *MockPlayerPoolRepository_AddPlayer_Call {
	return &MockPlayerPoolRepository_AddPlayer_Call{Call: _e.mock.On("AddPlayer", player)}
}

func (_c *MockPlayerPoolRepository_AddPlayer_Call) Run(run func(player *service.Player)) *MockPlayerPoolRepository_AddPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*service.Player))
	})
	return _c
}

func (_c *MockPlayerPoolRepository_AddPlayer_Call) Return(_a0 error) *MockPlayerPoolRepository_AddPlayer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerPoolRepository_AddPlayer_Call) RunAndReturn(run func(*service.Player) error) *MockPlayerPoolRepository_AddPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayer provides a mock function with given fields: id
func (_m *MockPlayerPoolRepository) GetPlayer(id int) (*service.Player, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayer")
	}

	var r0 *service.Player
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (*service.Player, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *service.Player); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPlayerPoolRepository_GetPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayer'
type MockPlayerPoolRepository_GetPlayer_Call struct {
	*mock.Call
}

// GetPlayer is a helper method to define mock.On call
//   - id int
func (_e *MockPlayerPoolRepository_Expecter) GetPlayer(id interface{}) *MockPlayerPoolRepository_GetPlayer_Call {
	return &MockPlayerPoolRepository_GetPlayer_Call{Call: _e.mock.On("GetPlayer", id)}
}

func (_c *MockPlayerPoolRepository_GetPlayer_Call) Run(run func(id int)) *MockPlayerPoolRepository_GetPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPlayerPoolRepository_GetPlayer_Call) Return(_a0 *service.Player, _a1 bool) *MockPlayerPoolRepository_GetPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerPoolRepository_GetPlayer_Call) RunAndReturn(run func(int) (*service.Player, bool)) *MockPlayerPoolRepository_GetPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlayer provides a mock function with given fields: answer, timeZone
func (_m *MockPlayerPoolRepository) NewPlayer(answer string, timeZone string) *service.Player {
	ret := _m.Called(answer, timeZone)

	if len(ret) == 0 {
		panic("no return value specified for NewPlayer")
	}

	var r0 *service.Player
	if rf, ok := ret.Get(0).(func(string, string) *service.Player); ok {
		r0 = rf(answer, timeZone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Player)
		}
	}

	return r0
}

// MockPlayerPoolRepository_NewPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPlayer'
type MockPlayerPoolRepository_NewPlayer_Call struct {
	*mock.Call
}

// NewPlayer is a helper method to define mock.On call
//   - answer string
//   - timeZone string
func (_e *MockPlayerPoolRepository_Expecter) NewPlayer(answer interface{}, timeZone interface{}) *MockPlayerPoolRepository_NewPlayer_Call {
	return &MockPlayerPoolRepository_NewPlayer_Call{Call: _e.mock.On("NewPlayer", answer, timeZone)}
}

func (_c *MockPlayerPoolRepository_NewPlayer_Call) Run(run func(answer string, timeZone string)) *MockPlayerPoolRepository_NewPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPlayerPoolRepository_NewPlayer_Call) Return(_a0 *service.Player) *MockPlayerPoolRepository_NewPlayer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerPoolRepository_NewPlayer_Call) RunAndReturn(run func(string, string) *service.Player) *MockPlayerPoolRepository_NewPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlayer provides a mock function with given fields: id
func (_m *MockPlayerPoolRepository) RemovePlayer(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlayer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerPoolRepository_RemovePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlayer'
type MockPlayerPoolRepository_RemovePlayer_Call struct {
	*mock.Call
}

// RemovePlayer is a helper method to define mock.On call
//   - id int
func (_e *MockPlayerPoolRepository_Expecter) RemovePlayer(id interface{}) *MockPlayerPoolRepository_RemovePlayer_Call {
	return &MockPlayerPoolRepository_RemovePlayer_Call{Call: _e.mock.On("RemovePlayer", id)}
}

func (_c *MockPlayerPoolRepository_RemovePlayer_Call) Run(run func(id int)) *MockPlayerPoolRepository_RemovePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPlayerPoolRepository_RemovePlayer_Call) Return(_a0 error) *MockPlayerPoolRepository_RemovePlayer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerPoolRepository_RemovePlayer_Call) RunAndReturn(run func(int) error) *MockPlayerPoolRepository_RemovePlayer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerPoolRepository creates a new instance of MockPlayerPoolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerPoolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerPoolRepository {
	mock := &MockPlayerPoolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
