// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTimeProviderRepository is an autogenerated mock type for the TimeProviderRepository type
type MockTimeProviderRepository struct {
	mock.Mock
}

type MockTimeProviderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimeProviderRepository) EXPECT() *MockTimeProviderRepository_Expecter {
	return &MockTimeProviderRepository_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with given fields: timeZone
func (_m *MockTimeProviderRepository) Now(timeZone string) time.Time {
	ret := _m.Called(timeZone)

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(timeZone)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockTimeProviderRepository_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockTimeProviderRepository_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
//   - timeZone string
func (_e *MockTimeProviderRepository_Expecter) Now(timeZone interface{}) *MockTimeProviderRepository_Now_Call {
	return &MockTimeProviderRepository_Now_Call{Call: _e.mock.On("Now", timeZone)}
}

func (_c *MockTimeProviderRepository_Now_Call) Run(run func(timeZone string)) *MockTimeProviderRepository_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTimeProviderRepository_Now_Call) Return(_a0 time.Time) *MockTimeProviderRepository_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimeProviderRepository_Now_Call) RunAndReturn(run func(string) time.Time) *MockTimeProviderRepository_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTimeProviderRepository creates a new instance of MockTimeProviderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimeProviderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimeProviderRepository {
	mock := &MockTimeProviderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
