name: CI/CD

on: 
    push: 
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Install dependencies
              run: | 
                   go get ./...

            - name: Test with the Go CLI
              run: go test ./...

    deploy:
        permissions: 
            contents: 'read'
            id-token: 'write'

        needs: test
        name: Deploy to GAE
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Authenticate to Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                  service_account: guess-the-number-425013@appspot.gserviceaccount.com
                  workload_identity_provider: ${secrets.GAE_WORKLOAD_IDENTITY_PROVIDER}

            - name: Deploy to GAE
              uses: 'google-github-actions/deploy-appengine@v2'
