name: CI/CD

on: 
    push: 
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Install dependencies
              run: | 
                   go get ./...
                   go get google.golang.org/appengine

            - name: Test with the Go CLI
              run: go test ./...

    deploy:
        permissions: 
            contents: 'read'
            id-token: 'write'

        needs: test
        name: Deploy to GAE
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - id: 'auth'
              name: Authentication to Google Cloud
              uses: 'google-github-actions/auth@v2'
              with:
                  project_id: ${{ secrets.GAE_PROJECT_ID }}
                  workload_identity_provider: ${{ secrets.GAE_WORKLOAD_IDENTITY_PROVIDER }}

            - id: 'deploy'
              name: Deployment to GAE
              uses: 'google-github-actions/deploy-appengine@v2'

            - id: 'ouput'
              name: Output from deployment
              run: 'curl "${{ steps.deploy.outputs.version_url }}"'

        
